# Python Programming Basic Assignment 13


### 1. Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 C D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [82]:
import math

# Fixed values of formula
C = 50
H = 30

# Enter the inputs in comma seperated sequence
numbers = input("Enter the numbers seperated by comma(,): ")
if len(numbers) == 0:
    print("Enter at least one number")
    
else:

    num_list = numbers.split(',')
    res_list = []

    # Iterate through every numbers in list and input it in formula
    for D in num_list:
        res = round(math.sqrt((2 * C * int(D)) / H))
        res_list.append(res)

    # Convert elements in list into string and join it
    for i in range(len(res_list)):
        res_list[i] = str(res_list[i])

    print(','.join(res_list))

Enter the numbers seperated by comma(,):  100,150,180


18,22,24


### 2. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

In [83]:
import numpy as np

num_2digit = input("Enter a two digit number: ")

# Check if number of digits is 2 or not
if len(num_2digit) != 2:
    print("Please enter a two digit number")
    
else:
    # Seperate first and second digit into row and column variable
    row_digit = int(num_2digit[0])
    col_digit = int(num_2digit[1])
    
    # prepare 2-d array using row and column variable as size and get random elements between 0 and 10
    array_2d = np.random.randint(0, 10, size = (row_digit, col_digit))
    
    print("\n2D Array:")
    print(array_2d)


Enter a two digit number:  34



2D Array:
[[7 8 3 5]
 [5 2 6 9]
 [1 5 5 4]]


### 3. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

In [84]:
words_seq = input("Enter random words: ")
words_seq_list = words_seq.lower().split(',')

# Check number of words entered
if len(words_seq_list) == 1:
    print("Enter a minimum of 2 words")
    
else:
    
    # Sort the words in list
    word_list = words_seq_list.copy()
    word_list.sort()
    
    print(','.join(word_list))
    

Enter random words:  data,analytics,check,test


analytics,check,data,test


### 4. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

In [87]:
words_seq = input("Enter the words seperated by space: ")
words_seq_list = words_seq.lower().split(' ')


# Check the number of words
if len(words_seq_list) == 1:
    print("Enter a minimum of 2 words")
    
else:
    
    unique_words = []
    
    # Check for unique words and append it in new list
    for word in words_seq_list:
        if word not in unique_words:
            unique_words.append(word)
    
    # Sort the unique words and join
    unique_words_sort = unique_words.copy()
    unique_words_sort.sort()

    print(' '.join(unique_words_sort))

Enter the words seperated by space:  hello world and practice makes perfect and hello world again


again and hello makes perfect practice world


### 5. Write a program that accepts a sentence and calculate the number of letters and digits.

In [88]:
words_seq = input("Enter the words seperated by space: ")
words_seq_list = list(words_seq)

# Check number of words
if len(words_seq_list) == 1:
    print("Enter a minimum of 2 words")
    
else:

    letters, digits = 0, 0
    
    # Count the number of letters and digits in list
    for word in words_seq_list:
        if word.isalpha():
            letters += 1
        elif word.isdigit():
            digits +=1
        else:
            pass
        
    print("Letters count : {}".format(letters))
    print("Digits count : {}".format(digits))

Enter the words seperated by space:  hello world @! 12345


Letters count : 10
Digits count : 5


### 6. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

In [75]:
import re
username = input("Enter the username: ")
password = input("Enter the password: ")

# Check whether username is blank or not.
if len(username) == 0:
    print("Username cannot be blank")
    
else:

    flag = True
    while flag:  
        # Password should have minimum length of 6 and maximum of 12 characters
        if (len(password)<6 or len(password)>12):
            break
            
        # Check for lower case letters
        elif not re.search("[a-z]",password):
            break
            
        # Check for number
        elif not re.search("[0-9]",password):
            break
            
        # Check for upper case characters
        elif not re.search("[A-Z]",password):
            break
            
        # Check for special characters
        elif not re.search("[$#@]",password):
            break
            
        # Check for white space
        elif re.search("\s",password):
            break
        else:
            print("Valid Password")
            flag=False
            break
            
if flag:
    print("Invalid Password.")
    print("Password should have minimum length of 6 and maximum of 12 characters.")
    print("Password should contain one lowercase letter.")
    print("Password should contain one uppercase letter.")
    print("Password should contain one number.")
    print("Password should contain one special characters.")
    print("Password should not contain blank spaces.")

Enter the username:  dataanalytics
Enter the password:  Data@123455


Valid Password
