# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [14]:
import numpy as np


# Get 9 random numbers from 1 to 10 and reshape into 3 x 3 matrix
arr1 = np.random.randint(1,10,9).reshape(3,3)
arr2 = np.random.randint(1,10,9).reshape(3,3)

sum_array = arr1 + arr2

print("Array 1:")
print("{}\n".format(arr1))
print("Array 2:")
print("{}\n".format(arr2))
print("Sum of Array:")
print("{}".format(sum_array))

Array 1:
[[8 2 6]
 [2 2 8]
 [2 8 5]]

Array 2:
[[8 7 9]
 [9 7 5]
 [4 8 9]]

Sum of Array:
[[16  9 15]
 [11  9 13]
 [ 6 16 14]]


### 2. Write a Python Program to Multiply Two Matrices?

In [19]:
import numpy as np


# Get 9 random numbers from 1 to 10 and reshape into 3 x 3 matrix
arr1 = np.random.randint(1,10,9).reshape(3,3)
arr2 = np.random.randint(1,10,9).reshape(3,3)

# Matrix Multiplication using dot function
mult_array = np.dot(arr1 , arr2)

print("Array 1:")
print("{}\n".format(arr1))
print("Array 2:")
print("{}\n".format(arr2))
print("Multiplication of Array:")
print("{}".format(mult_array))

Array 1:
[[4 4 5]
 [6 2 6]
 [3 8 1]]

Array 2:
[[5 3 9]
 [3 2 2]
 [8 7 3]]

Multiplication of Array:
[[72 55 59]
 [84 64 76]
 [47 32 46]]


### 3. Write a Python Program to Transpose a Matrix?

In [20]:
# Transpose matrix means column data is converted to row data and vice versa
import numpy as np


# Get 9 random numbers from 1 to 10 and reshape into 3 x 3 matrix
arr = np.random.randint(1,10,9).reshape(3,3)

arr_transpose = arr.transpose()

print("Array:")
print("{}\n".format(arr))
print("Transpose of Array:")
print("{}".format(arr_transpose))

Array:
[[4 9 5]
 [7 5 5]
 [1 1 9]]

Transpose of Array:
[[4 7 1]
 [9 5 1]
 [5 5 9]]



### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [32]:
my_str = "The Quick Brown Fox Jumps Over the Lazy Dog"

# Convert all words into lower case and then split the sentence 
my_str_split = my_str.lower().split()
print("Before Sorting: {}".format(my_str_split))

my_str_split.sort()
print("After Sorting: {}".format(my_str_split))


Before Sorting: ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
After Sorting: ['brown', 'dog', 'fox', 'jumps', 'lazy', 'over', 'quick', 'the', 'the']


### 5. Write a Python Program to Remove Punctuation From a String?

In [33]:
import string
my_str = "The :Quick ;Brown Fox, Jumps. Over !the @Lazy Dog"
print("Before removing punctuation: {}".format(my_str))

my_str = my_str.translate(str.maketrans('', '', string.punctuation))
print("After removing punctuation: {}".format(my_str))

Before removing punctuation: The :Quick ;Brown Fox, Jumps. Over !the @Lazy Dog
After removing punctuation: The Quick Brown Fox Jumps Over the Lazy Dog
